# Generated by Django 2.0.1 on 2018-03-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titleImg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
