# Generated by Django 2.0.1 on 2018-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_post_titleimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titleImg',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
