# Generated by Django 2.0.1 on 2018-04-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_auto_20180321_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='beta',
            field=models.NullBooleanField(),
        ),
    ]
