# Generated by Django 2.0.1 on 2018-03-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='editedParams',
            field=models.BooleanField(),
        ),
    ]
