# Generated by Django 2.0.1 on 2018-03-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180322_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='horizontal',
            field=models.BooleanField(default=False),
        ),
    ]
